
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: localhost:9092

logging:
  level:
    org.apache.kafka: info
